name: Angular CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm

      - name: Install all the depenedencies
        run: npm ci

      - name: Build the Angular Application
        run: npm run build

  dockerize_and_push:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      node-version: "22"
      publish-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      image-name: cap-stone-project-image
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
