name: Capstone CI Project

on:
  push:
    branches:
      - main

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test -- --no-watch --coverage

      - name: Build application
        run: npm run build

  dockerize_and_push:
    uses: ./.github/workflows/docker-build-template.yaml
    needs: build
    with:
      node-version: "22"
      publish-image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      image-name: cap-stone-project-image
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

  deploy_production:
    name: Deploy to Production
    needs: [build, dockerize_and_push]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://company.com
    steps:
      - name: Deploy the image to the Production.
        env:
          ENV_LABEL: ${{vars.PROD_LABEL}}
          IMAGE_TAG: sha-${{github.sha}}
        run: |
          echo "Deploying to the Production server with environment ${ENV_LABEL} and tag ${IMAGE_TAG}"
          # docker container run -d -p 8080:8080 -e APP_ENVIRONMENT="$ENV_LABEL" ${{env.REGISTRY}}/${{env}}
